site_name: Jollista
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: slate
    primary: pink
    accent: pink

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Games: games.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false